// Plain words (Version 17). The site is written for enthusiasts first; Simple view adds a one-line, jargon-free explanation
// under the spec rows a newcomer is most likely to trip over, and the glossary (Methodology page, and the search box)
// explains every tech word the hub uses. These are general explanations, not claims about any particular device.

// Keyed by the spec-row label as the category files name it.
export const PLAIN_BY_LABEL = {
  'Max refresh rate': 'How many times a second the screen redraws. 120 Hz looks smoother than 60 Hz when you scroll.',
  'Refresh rate': 'How many times a second the screen redraws. Higher looks smoother when you scroll.',
  'Peak brightness (claimed)': 'The maker’s brightest figure (nits), usually for small bright areas. Higher helps outdoors in sunlight.',
  'Pixel density': 'Pixels per inch. Above about 400, most people cannot see individual dots.',
  Resolution: 'How many dots make up the picture. More dots means sharper text and photos.',
  Panel: 'The screen technology. OLED/AMOLED screens have deep blacks; LCD screens are usually cheaper.',
  Chip: 'The processor inside. It decides how smooth the device feels and how long the battery lasts.',
  'Screen size': 'Measured corner to corner.',
  'Capacity (mAh)': 'Battery size. Bigger usually lasts longer.',
  'Water resistance': 'How much water it can take. 5 ATM is fine for swimming; it is not for diving.',
  'Low-power mode (claimed)': 'How long it lasts with most smart features switched off.',
  'Satellite SOS': 'Can send an emergency message by satellite where there is no mobile signal.',
  'Case size': 'The size of the charging case you carry around. The Size section draws it next to a bank card.',
  Style: 'How the earbuds sit: in-ear tips seal the ear (better noise blocking); open or half in-ear designs feel lighter.',
  'Wireless charging case': 'The case can be charged on a wireless pad, no cable needed.',
  'Earbuds alone, noise cancelling on': 'Listening time with noise cancelling switched on; it uses more battery.',
  'Spatial / 3D audio': 'Sound that seems to come from around you, like a cinema, with supported videos and music.',
  Chipset: 'The phone’s “brain”. It decides how fast apps open, how well games run and how much battery it uses.',
  CPU: 'The main processor cores inside the chip. More and faster cores help with heavy apps.',
  GPU: 'The graphics part of the chip. It matters most for games.',
  RAM: 'Working memory. More RAM keeps more apps open at once without reloading.',
  Storage: 'Space for apps, photos and videos. 128 GB suits light use; 256 GB or more if you shoot lots of video.',
  'Card slot': 'Whether you can add a microSD memory card for extra storage.',
  Capacity: 'Battery size in mAh. Bigger usually lasts longer, but the chip and screen matter as much.',
  'Wired charging': 'The fastest charging speed with a cable, in watts. Higher fills the battery faster.',
  'Wireless charging': 'Charging by placing the device on a pad, no cable. Slower than a cable but convenient.',
  'Reverse charging': 'Using this device to charge another one, such as earbuds or a watch.',
  'Ingress protection': 'The IP rating: how well it keeps out dust and water. IP68 can survive being dropped in water.',
  'Water & dust rating (earbuds)': 'The IP rating of the earbuds: how well they handle sweat, rain and dust. IP54 is splash-proof.',
  'Water & dust rating (case)': 'The IP rating of the charging case, often lower than the earbuds’ own rating.',
  Weight: 'How heavy it is. For phones, under about 190 g feels light; over 220 g feels heavy.',
  Dimensions: 'Height × width × thickness in millimetres. The Size section draws it next to a bank card.',
  Cameras: 'The cameras on the back. The main camera matters most; ultra-wide fits more in, telephoto zooms in without losing detail.',
  'Longest optical zoom': 'How far the camera zooms using real lenses (no quality loss). Beyond that it is digital zoom.',
  Video: 'The best video quality it records. 4K is sharper than 1080p.',
  'OS upgrade commitment': 'How many years of new Android or iOS versions the maker promises.',
  'Security update commitment': 'How many years of security fixes the maker promises. Longer means the device stays safe to use for longer.',
  NFC: 'Tap-to-pay and quick pairing. Needed for paying with your phone or watch.',
  'Wi-Fi': 'Wireless internet standard. Wi-Fi 6 and 7 are faster than Wi-Fi 5 with a newer router.',
  Bluetooth: 'Wireless link to earbuds, watches and cars. Newer versions connect more reliably.',
  '3.5 mm jack': 'A socket for wired headphones.',
  'Fastest network': 'The fastest mobile network it supports. 5G is faster than 4G where coverage exists.',
  'Active noise cancelling': 'Microphones listen to outside noise and cancel it, so you hear less of buses, planes and fans.',
  'Bluetooth codecs': 'How music is squeezed for Bluetooth. AAC suits iPhones; LDAC and aptX can sound better with Android phones.',
  'Speaker driver': 'The tiny speaker inside each earbud. Size alone does not decide sound quality.',
  'Earbuds alone (claimed, longest)': 'Listening time from one full charge of the earbuds, as the maker claims.',
  'With the charging case (claimed, longest)': 'Total listening time including recharges from the case.',
  'Two devices at once (multipoint)': 'Stay connected to your phone and laptop at the same time and switch automatically.',
  'Battery life (claimed)': 'How long the maker says one charge lasts in typical use.',
  'OS at launch': 'The software version it came with.',
};

// The glossary: every tech word the hub uses, in plain words. Also searchable from the site search.
export const GLOSSARY = [
  ['mAh', 'Milliampere-hours: how much charge a battery holds. More mAh usually means longer battery life, but the chip and screen matter as much.'],
  ['W (watts)', 'Charging speed. A 45 W charger fills a battery much faster than a 15 W one.'],
  ['IP68 / IP67 / IP54', 'Ingress protection. The first digit is dust (6 = dust-tight), the second water (8 = survives immersion, 7 = short immersion, 4 = splashes).'],
  ['5 ATM', 'Watch water rating: fine for swimming in a pool, not for diving.'],
  ['OLED / AMOLED', 'A screen where every pixel makes its own light: deep blacks, strong colours, good battery use with dark themes.'],
  ['LTPO', 'A screen that can slow its refresh rate right down (even to 1 Hz) when nothing moves, to save battery.'],
  ['LCD', 'An older, cheaper screen type lit from behind. Blacks look grey rather than truly black.'],
  ['Refresh rate (Hz)', 'How many times a second the screen redraws. 120 Hz looks smoother than 60 Hz.'],
  ['Nits', 'Screen brightness. Around 1,000 nits and up is comfortable outdoors.'],
  ['PPI', 'Pixels per inch: how sharp the screen is. Above about 400 looks crisp to most people.'],
  ['Chipset / SoC', 'The main chip that runs everything: processor, graphics, AI and modem in one.'],
  ['RAM', 'Working memory that keeps apps open. 8 GB is comfortable for most phones today.'],
  ['UFS', 'The type of storage chip. Newer versions (UFS 4) load apps and copy files faster.'],
  ['Geekbench', 'A benchmark app that scores how fast the processor is. Higher is faster.'],
  ['AnTuTu', 'A benchmark that mixes processor, graphics and memory into one score.'],
  ['3DMark / Wild Life', 'Graphics benchmarks for games. The stress test shows how much speed a phone keeps when it gets hot.'],
  ['Thermal throttling', 'When a device slows itself down to avoid overheating during long games or video recording.'],
  ['DXOMARK', 'A lab that scores cameras with the same tests for every phone.'],
  ['Main / ultra-wide / telephoto', 'The main camera is the best one; ultra-wide fits more in; telephoto zooms in with a real lens.'],
  ['Periscope', 'A telephoto lens folded sideways inside the phone, so it can zoom further (usually 3x–5x or more).'],
  ['Optical zoom', 'Zoom using lenses, with no loss of detail. Digital zoom just enlarges the picture.'],
  ['OIS', 'Optical image stabilisation: the lens moves to cancel hand shake, for sharper night photos and steadier video.'],
  ['Megapixels (MP)', 'How many million dots a photo has. More is not always better; sensor size and processing matter more.'],
  ['ANC', 'Active noise cancelling: earbuds or headphones cancel outside noise with microphones.'],
  ['Transparency mode', 'The opposite of ANC: earbuds let outside sound in so you can hear traffic or announcements.'],
  ['Codec (AAC, LDAC, aptX)', 'How Bluetooth music is compressed. LDAC and aptX can carry more detail than SBC or AAC on supported phones.'],
  ['Multipoint', 'Earbuds connected to two devices at once, such as a phone and a laptop.'],
  ['Hi-Res Audio', 'Certified to play higher-quality music files, if the phone and the song support it.'],
  ['eSIM', 'A SIM built into the phone, set up by scanning a code from your carrier instead of inserting a card.'],
  ['NFC', 'Short-range wireless used for tap-to-pay and quick pairing.'],
  ['Wi-Fi 6 / 6E / 7', 'Newer Wi-Fi standards: faster and better in crowded places, with a matching router.'],
  ['UWB', 'Ultra-wideband: precise location between devices, used for item trackers and digital car keys.'],
  ['ECG', 'An electrical heart reading some watches take, to look for irregular rhythms.'],
  ['SpO2', 'Blood-oxygen level, estimated by a watch or band from light shone into the skin.'],
  ['Dual-band GPS', 'GPS that listens on two frequencies, so it stays accurate between tall buildings.'],
  ['Launch price', 'The price when the device went on sale. Shops often sell for less later.'],
  ['Claimed vs measured', 'Claimed is what the maker says; measured is what an independent lab or reviewer recorded. The hub labels which is which.'],
  ['Confidence', 'How sure the hub is about a value: several agreeing independent sources give high confidence.'],
  ['Platform score', 'The hub’s own 0–100 score from recorded specifications and tests, compared with devices of the same kind.'],
];
