// Flagship lines (Version 14): each brand's top models in launch order, oldest first. The Charts page draws one line
// per series through the years, and tools/generation_check.mjs compares every model with its predecessor.
// Only consecutive, like-for-like models of one line belong together.

export const LINES = [
  ['Galaxy S Ultra', 'samsung', ['samsung-galaxy-s23-ultra', 'samsung-galaxy-s24-ultra', 'samsung-galaxy-s25-ultra', 'samsung-galaxy-s26-ultra']],
  ['Galaxy S+', 'samsung', ['samsung-galaxy-s23-plus', 'samsung-galaxy-s24-plus', 'samsung-galaxy-s25-plus', 'samsung-galaxy-s26-plus']],
  ['Galaxy S', 'samsung', ['samsung-galaxy-s23', 'samsung-galaxy-s24', 'samsung-galaxy-s25', 'samsung-galaxy-s26']],
  ['Galaxy S FE', 'samsung', ['samsung-galaxy-s23-fe', 'samsung-galaxy-s24-fe', 'samsung-galaxy-s25-fe', 'samsung-galaxy-s26-fe']],
  ['Galaxy Z Fold', 'samsung', ['samsung-galaxy-z-fold5', 'samsung-galaxy-z-fold6', 'samsung-galaxy-z-fold7', 'samsung-galaxy-z-fold8']],
  ['Galaxy Z Flip', 'samsung', ['samsung-galaxy-z-flip5', 'samsung-galaxy-z-flip6', 'samsung-galaxy-z-flip7', 'samsung-galaxy-z-flip8']],
  ['iPhone Pro Max', 'apple', ['apple-iphone-15-pro-max', 'apple-iphone-16-pro-max', 'apple-iphone-17-pro-max', 'apple-iphone-18-pro-max']],
  ['iPhone Pro', 'apple', ['apple-iphone-15-pro', 'apple-iphone-16-pro', 'apple-iphone-17-pro', 'apple-iphone-18-pro']],
  ['iPhone', 'apple', ['apple-iphone-15', 'apple-iphone-16', 'apple-iphone-17']],
  ['iPhone Plus', 'apple', ['apple-iphone-15-plus', 'apple-iphone-16-plus']],
  ['Pixel Pro XL', 'google', ['google-pixel-10-pro-xl', 'google-pixel-11-pro-xl']],
  ['Pixel Pro', 'google', ['google-pixel-10-pro', 'google-pixel-11-pro']],
  ['Pixel', 'google', ['google-pixel-10', 'google-pixel-11']],
  ['Xiaomi Ultra', 'xiaomi', ['xiaomi-13-ultra', 'xiaomi-14-ultra', 'xiaomi-15-ultra', 'xiaomi-17-ultra']],
  ['Xiaomi', 'xiaomi', ['xiaomi-13', 'xiaomi-14', 'xiaomi-15', 'xiaomi-17']],
  ['Xiaomi T Pro', 'xiaomi', ['xiaomi-13t-pro', 'xiaomi-14t-pro', 'xiaomi-15t-pro', 'xiaomi-17t-pro']],
  ['Xiaomi T', 'xiaomi', ['xiaomi-13t', 'xiaomi-14t', 'xiaomi-15t', 'xiaomi-17t']],
  ['POCO F Pro', 'poco', ['poco-f5-pro', 'poco-f6-pro', 'poco-f7-pro', 'poco-f8-pro', 'poco-f9-pro']],
  ['POCO F Ultra', 'poco', ['poco-f7-ultra', 'poco-f8-ultra', 'poco-f9-ultra']],
  ['POCO F', 'poco', ['poco-f5', 'poco-f6', 'poco-f7', 'poco-f8']],
  ['OPPO Find X Pro', 'oppo', ['oppo-find-x8-pro', 'oppo-find-x9-pro']],
  ['OPPO Find X', 'oppo', ['oppo-find-x8', 'oppo-find-x9', 'oppo-find-x10']],
  ['OPPO Find N', 'oppo', ['oppo-find-n3', 'oppo-find-n5', 'oppo-find-n6']],
  ['vivo X Pro', 'vivo', ['vivo-x90-pro', 'vivo-x100-pro', 'vivo-x200-pro', 'vivo-x300-pro', 'vivo-x500-pro']],
  ['vivo X', 'vivo', ['vivo-x90', 'vivo-x100', 'vivo-x200', 'vivo-x300', 'vivo-x500']],
  ['vivo X Ultra', 'vivo', ['vivo-x200-ultra', 'vivo-x300-ultra']],
  ['iQOO', 'iqoo', ['iqoo-11', 'iqoo-12', 'iqoo-13', 'iqoo-15']],
  ['HONOR Magic Pro', 'honor', ['honor-magic5-pro', 'honor-magic6-pro', 'honor-magic7-pro', 'honor-magic8-pro']],
  ['HONOR Magic V', 'honor', ['honor-magic-v2', 'honor-magic-v3', 'honor-magic-v5', 'honor-magic-v6']],
  ['Huawei Pura Ultra', 'huawei', ['huawei-pura-70-ultra', 'huawei-pura-80-ultra']],
  ['Huawei Pura Pro', 'huawei', ['huawei-pura-70-pro', 'huawei-pura-80-pro']],
  ['Huawei Mate X', 'huawei', ['huawei-mate-x3', 'huawei-mate-x6', 'huawei-mate-x7']],
  ['OnePlus', 'oneplus', ['oneplus-13', 'oneplus-15']],
];
